function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("@render:", "use_fixed_fit_projection", { near = -1, far = 1 })

	local n = 1
	for j = 1, 10 do
		for i = 1, 20 do
			local pos = vmath.vector3(i * 64, j * 64, 2 + (j * 20 + i) / 1000)
			factory.create("#sprite" .. n, pos)
			n = n + 1
			if n > 2 then n = 1 end
		end
	end
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		msg.post("@system:", "toggle_profile")
	end
end
